site_name: Runtime Editor
site_url: http://rteditor.battlehub.net
site_description: Documentation for Runtime Editor - runtime scene editor built with Unity3D
site_author: vadim andriyanov
copyright: Copyright © 2019 vadim.andriyanov@outlook.com 
nav:
    - Home: 'index.md'
    - General: 'general.md'
    - Getting Started: 'get-started.md'
    - Transform Handles: 'transform-handles.md'
    - Gizmos: 'gizmos.md'
    - Rendering: 'rendering.md'
    - Common Infrastructure: 'infrastructure.md'
    - Runtime Editor: 'runtime-editor.md'
    - Save Load: 'save-load.md' 
    - Dock Panels: 'dock-panels.md'
    - Virtualizing Tree View: 'vtv.md'
    - Menu Control: 'menu-control.md'
 
theme: readthedocs
markdown_extensions:
  - admonition

