site_name: Runtime Editor
site_url: http://rteditor.battlehub.net
site_description: Documentation for Runtime Editor - runtime scene editor built with Unity3D
site_author: vadim andriyanov
copyright: Copyright © 2019 vadim.andriyanov@outlook.com 
nav:
    - Home: 'index.md'
    - General: 'general.md'
    - Getting Started: 'getting_started.md'
    - Transform Handles: 'transform_handles.md'
    - Gizmos: 'gizmos.md'
    - Gizmos And Handles rendering: 'gizmos_and_handles_rendering'
        
        
      
   
theme: readthedocs
markdown_extensions:
  - admonition

